export const actions = {
  REQUEST: 'DATA_RESPONSE_REQUEST',
  SUCCESS: 'DATA_RESPONSE_SUCCESS',
  ERROR: 'DATA_RESPONSE_ERROR',
  TASK_UPDATE: 'DATA_TASK_UPDATE',
  NEW_TASK: 'DATA_NEW_TASK',
  TASK_DELETE: 'DATA_TASK_DELETE',
  USER_UPDATE: 'DATA_USER_UPDATE',
  RESET_THEME: 'RESET_THEME',
  TOGGLE_THEME: 'TOGGLE_THEME',
};
