export const actions = {
  REQUEST: 'DATA_RESPONSE_REQUEST',
  SUCCESS: 'DATA_RESPONSE_SUCCESS',
  ERROR: 'DATA_RESPONSE_ERROR',
  UPDATE: 'DATA_UPDATE',
  RESET_THEME: 'RESET_THEME',
  TOGGLE_THEME: 'TOGGLE_THEME',
};
